name: "data_days_demo_dbt"
version: "1.0.0"
config-version: 2

profile: "data_days_demo_dbt"

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: table
